/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproject;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
/**
 *
 * @author Ivan
 */
public class MainMenu extends javax.swing.JFrame {
    /**
     * Creates new form MainMenu
     */
    Staff staff;
    Connect con;
    
    public MainMenu(Staff staff) {
        initComponents();
        setTitle("Main Menu");
        setLocationRelativeTo(null);
        con = new Connect();
        this.staff = staff;
        
        txtEmployeeID.setText(staff.getEmployeeID());
        txtFirstName.setText(staff.getFirstname());
        txtMiddleName.setText(staff.getMiddlename());
        txtLastName.setText(staff.getLastname());
        if(staff.getIsnew()) {
            CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
            cardLayout.show(pnlCardLayout, "card7");
            btnAdmitPatient.setEnabled(false);
            btnCheckPatientRecord.setEnabled(false);
            btnDischargePatient.setEnabled(false);
            btnCheckPatientBalance.setEnabled(false);
            btnSettlePatientBalance.setEnabled(false);
            btnSettings.setEnabled(false);
            
        } else {
            CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
            cardLayout.show(pnlCardLayout, "card6");
        }
        
    }
    
    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        con = new Connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        btnAdmitPatient = new javax.swing.JButton();
        btnCheckPatientRecord = new javax.swing.JButton();
        btnDischargePatient = new javax.swing.JButton();
        btnCheckPatientBalance = new javax.swing.JButton();
        btnSettlePatientBalance = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        pnlCardLayout = new javax.swing.JPanel();
        pnlAdmitPatient = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlCheckPatientRecord = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlDischargePatient = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlCheckPatientBalance = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlSettlePatientBalance = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlNewAccount = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pfNewPassword = new javax.swing.JPasswordField();
        pfConfirmPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pnlAccountSettings = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnChangePass = new javax.swing.JButton();
        txtEmployeeID = new javax.swing.JLabel();
        txtMiddleName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pnlChangePassword = new javax.swing.JPanel();
        btnChange = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        pfConfirmPassword1 = new javax.swing.JPasswordField();
        pfNewPassword1 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pfEnterPassword = new javax.swing.JPasswordField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management System");
        setSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(73, 57, 121));

        btnAdmitPatient.setBackground(new java.awt.Color(73, 57, 121));
        btnAdmitPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmitPatient.setText("Admit Patient");
        btnAdmitPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmitPatientActionPerformed(evt);
            }
        });

        btnCheckPatientRecord.setBackground(new java.awt.Color(73, 57, 121));
        btnCheckPatientRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckPatientRecord.setText("Check Patient's Record");
        btnCheckPatientRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckPatientRecordActionPerformed(evt);
            }
        });

        btnDischargePatient.setBackground(new java.awt.Color(73, 57, 121));
        btnDischargePatient.setForeground(new java.awt.Color(255, 255, 255));
        btnDischargePatient.setText("Discharge Patient ");
        btnDischargePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDischargePatientActionPerformed(evt);
            }
        });

        btnCheckPatientBalance.setBackground(new java.awt.Color(73, 57, 121));
        btnCheckPatientBalance.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckPatientBalance.setText("Check Patient's Balance");
        btnCheckPatientBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckPatientBalanceActionPerformed(evt);
            }
        });

        btnSettlePatientBalance.setBackground(new java.awt.Color(73, 57, 121));
        btnSettlePatientBalance.setForeground(new java.awt.Color(255, 255, 255));
        btnSettlePatientBalance.setText("Settle Patient's Balance");
        btnSettlePatientBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettlePatientBalanceActionPerformed(evt);
            }
        });

        btnSignOut.setBackground(new java.awt.Color(73, 57, 121));
        btnSignOut.setForeground(new java.awt.Color(255, 255, 255));
        btnSignOut.setText("Sign out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        btnSettings.setBackground(new java.awt.Color(73, 57, 121));
        btnSettings.setForeground(new java.awt.Color(255, 255, 255));
        btnSettings.setText("Account Settings");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSettlePatientBalance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnCheckPatientBalance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnDischargePatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnAdmitPatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnCheckPatientRecord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAdmitPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnCheckPatientRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDischargePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnCheckPatientBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSettlePatientBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pnlCardLayout.setLayout(new java.awt.CardLayout());

        pnlAdmitPatient.setBackground(new java.awt.Color(254, 251, 245));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Admit Patient");

        javax.swing.GroupLayout pnlAdmitPatientLayout = new javax.swing.GroupLayout(pnlAdmitPatient);
        pnlAdmitPatient.setLayout(pnlAdmitPatientLayout);
        pnlAdmitPatientLayout.setHorizontalGroup(
            pnlAdmitPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdmitPatientLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel5)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        pnlAdmitPatientLayout.setVerticalGroup(
            pnlAdmitPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdmitPatientLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlAdmitPatient, "card6");

        pnlCheckPatientRecord.setBackground(new java.awt.Color(254, 251, 245));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Check Patient's Record");

        javax.swing.GroupLayout pnlCheckPatientRecordLayout = new javax.swing.GroupLayout(pnlCheckPatientRecord);
        pnlCheckPatientRecord.setLayout(pnlCheckPatientRecordLayout);
        pnlCheckPatientRecordLayout.setHorizontalGroup(
            pnlCheckPatientRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCheckPatientRecordLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(223, 223, 223))
        );
        pnlCheckPatientRecordLayout.setVerticalGroup(
            pnlCheckPatientRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckPatientRecordLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlCheckPatientRecord, "card2");

        pnlDischargePatient.setBackground(new java.awt.Color(254, 251, 245));

        jLabel2.setText("Discharge Patient");

        javax.swing.GroupLayout pnlDischargePatientLayout = new javax.swing.GroupLayout(pnlDischargePatient);
        pnlDischargePatient.setLayout(pnlDischargePatientLayout);
        pnlDischargePatientLayout.setHorizontalGroup(
            pnlDischargePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDischargePatientLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel2)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        pnlDischargePatientLayout.setVerticalGroup(
            pnlDischargePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDischargePatientLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlDischargePatient, "card3");

        pnlCheckPatientBalance.setBackground(new java.awt.Color(254, 251, 245));

        jLabel3.setText("Check Patient's Balance");

        javax.swing.GroupLayout pnlCheckPatientBalanceLayout = new javax.swing.GroupLayout(pnlCheckPatientBalance);
        pnlCheckPatientBalance.setLayout(pnlCheckPatientBalanceLayout);
        pnlCheckPatientBalanceLayout.setHorizontalGroup(
            pnlCheckPatientBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCheckPatientBalanceLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(224, 224, 224))
        );
        pnlCheckPatientBalanceLayout.setVerticalGroup(
            pnlCheckPatientBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckPatientBalanceLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlCheckPatientBalance, "card4");

        pnlSettlePatientBalance.setBackground(new java.awt.Color(254, 251, 245));

        jLabel4.setText("Settle Patient's Balance");

        javax.swing.GroupLayout pnlSettlePatientBalanceLayout = new javax.swing.GroupLayout(pnlSettlePatientBalance);
        pnlSettlePatientBalance.setLayout(pnlSettlePatientBalanceLayout);
        pnlSettlePatientBalanceLayout.setHorizontalGroup(
            pnlSettlePatientBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSettlePatientBalanceLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(224, 224, 224))
        );
        pnlSettlePatientBalanceLayout.setVerticalGroup(
            pnlSettlePatientBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettlePatientBalanceLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlSettlePatientBalance, "card5");

        pnlNewAccount.setBackground(new java.awt.Color(254, 251, 245));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("New Account");

        pfConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        jLabel7.setText("Enter New Password:");

        jLabel8.setText("Confirm New Password");

        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        jLabel9.setText("Please change your default password");

        javax.swing.GroupLayout pnlNewAccountLayout = new javax.swing.GroupLayout(pnlNewAccount);
        pnlNewAccount.setLayout(pnlNewAccountLayout);
        pnlNewAccountLayout.setHorizontalGroup(
            pnlNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewAccountLayout.createSequentialGroup()
                .addGroup(pnlNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewAccountLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel6))
                    .addGroup(pnlNewAccountLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel9))
                    .addGroup(pnlNewAccountLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(pnlNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNewAccountLayout.createSequentialGroup()
                                .addGroup(pnlNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(pnlNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pfNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(pfConfirmPassword)))
                            .addGroup(pnlNewAccountLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btnChangePassword)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        pnlNewAccountLayout.setVerticalGroup(
            pnlNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewAccountLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(95, 95, 95)
                .addGroup(pnlNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlNewAccount, "card7");

        pnlAccountSettings.setBackground(new java.awt.Color(254, 251, 245));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Account Details");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Employee ID");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("First Name");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Middle Name");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Last Name");

        btnChangePass.setText("Change Password");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        txtEmployeeID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmployeeID.setText("jLabel15");

        txtMiddleName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMiddleName.setText("jLabel15");

        txtFirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFirstName.setText("jLabel15");

        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLastName.setText("jLabel15");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccountSettingsLayout = new javax.swing.GroupLayout(pnlAccountSettings);
        pnlAccountSettings.setLayout(pnlAccountSettingsLayout);
        pnlAccountSettingsLayout.setHorizontalGroup(
            pnlAccountSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountSettingsLayout.createSequentialGroup()
                .addGroup(pnlAccountSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccountSettingsLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(pnlAccountSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAccountSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMiddleName, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                    .addGroup(pnlAccountSettingsLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlAccountSettingsLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(pnlAccountSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChangePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAccountSettingsLayout.setVerticalGroup(
            pnlAccountSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountSettingsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addGroup(pnlAccountSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtEmployeeID))
                .addGap(18, 18, 18)
                .addGroup(pnlAccountSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtFirstName))
                .addGap(18, 18, 18)
                .addGroup(pnlAccountSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMiddleName))
                .addGap(18, 18, 18)
                .addGroup(pnlAccountSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtLastName))
                .addGap(36, 36, 36)
                .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jButton2.getAccessibleContext().setAccessibleDescription("");

        pnlCardLayout.add(pnlAccountSettings, "card8");

        pnlChangePassword.setBackground(new java.awt.Color(254, 251, 245));

        btnChange.setText("Change Password");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        jLabel15.setText("Confirm New Password");

        pfConfirmPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        jLabel16.setText("Enter Password:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setText("Change Password");

        jLabel19.setText("Enter New Password:");

        javax.swing.GroupLayout pnlChangePasswordLayout = new javax.swing.GroupLayout(pnlChangePassword);
        pnlChangePassword.setLayout(pnlChangePasswordLayout);
        pnlChangePasswordLayout.setHorizontalGroup(
            pnlChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChangePasswordLayout.createSequentialGroup()
                .addGroup(pnlChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChangePasswordLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel17))
                    .addGroup(pnlChangePasswordLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(pnlChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChangePasswordLayout.createSequentialGroup()
                                .addGroup(pnlChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(pnlChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pfNewPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(pfConfirmPassword1)
                                    .addComponent(pfEnterPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                            .addGroup(pnlChangePasswordLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btnChange))))
                    .addGroup(pnlChangePasswordLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel18)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        pnlChangePasswordLayout.setVerticalGroup(
            pnlChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChangePasswordLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(44, 44, 44)
                .addGroup(pnlChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfEnterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfNewPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfConfirmPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlChangePassword, "card9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnCheckPatientRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckPatientRecordActionPerformed
        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card2");
    }//GEN-LAST:event_btnCheckPatientRecordActionPerformed

    private void btnDischargePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDischargePatientActionPerformed
        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card3");
    }//GEN-LAST:event_btnDischargePatientActionPerformed

    private void btnCheckPatientBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckPatientBalanceActionPerformed
        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card4");
    }//GEN-LAST:event_btnCheckPatientBalanceActionPerformed

    private void btnSettlePatientBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettlePatientBalanceActionPerformed
        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card5");
    }//GEN-LAST:event_btnSettlePatientBalanceActionPerformed

    private void btnAdmitPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmitPatientActionPerformed
        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card6");
    }//GEN-LAST:event_btnAdmitPatientActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
       String newpassword = pfNewPassword.getText();
       String confirm = pfConfirmPassword.getText();
       
       if(newpassword.length() < 8) {
            JOptionPane.showMessageDialog(null, "Password should atleast have 8 characters", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
       if(newpassword.equals(confirm)) {
           newpassword = staff.encryptPassword(newpassword);
           staff.setPassword(newpassword);
           con.updateIsNew(staff);
           
           if(con.changePassword(staff)) {
                JOptionPane.showMessageDialog(null, "Password changed!");
                btnAdmitPatient.setEnabled(true);
                btnCheckPatientRecord.setEnabled(true);
                btnDischargePatient.setEnabled(true);
                btnCheckPatientBalance.setEnabled(true);
                btnSettlePatientBalance.setEnabled(true);
                btnSettings.setEnabled(true);
                CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
                cardLayout.show(pnlCardLayout, "card6");
                
            }
       } else {
           JOptionPane.showMessageDialog(null, "Password does not match!", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card9");
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card6");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        String password = pfEnterPassword.getText();
        String newpassword = pfNewPassword1.getText();
        String confirm = pfConfirmPassword1.getText();
        
        if(newpassword.length() < 8) {
            JOptionPane.showMessageDialog(null, "Password should atleast have 8 characters", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        password = staff.encryptPassword(password);
        if(staff.getPassword().equals(password)) {
            if(newpassword.equals(confirm)) {
                newpassword = staff.encryptPassword(newpassword);
                staff.setPassword(newpassword);
                if(con.changePassword(staff)) {
                    JOptionPane.showMessageDialog(null, "Password changed!");
                    CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
                    cardLayout.show(pnlCardLayout, "card8");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Password does not match!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Incorrect Password!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card8");
    }//GEN-LAST:event_btnSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmitPatient;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnCheckPatientBalance;
    private javax.swing.JButton btnCheckPatientRecord;
    private javax.swing.JButton btnDischargePatient;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnSettlePatientBalance;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField pfConfirmPassword;
    private javax.swing.JPasswordField pfConfirmPassword1;
    private javax.swing.JPasswordField pfEnterPassword;
    private javax.swing.JPasswordField pfNewPassword;
    private javax.swing.JPasswordField pfNewPassword1;
    private javax.swing.JPanel pnlAccountSettings;
    private javax.swing.JPanel pnlAdmitPatient;
    private javax.swing.JPanel pnlCardLayout;
    private javax.swing.JPanel pnlChangePassword;
    private javax.swing.JPanel pnlCheckPatientBalance;
    private javax.swing.JPanel pnlCheckPatientRecord;
    private javax.swing.JPanel pnlDischargePatient;
    private javax.swing.JPanel pnlNewAccount;
    private javax.swing.JPanel pnlSettlePatientBalance;
    private javax.swing.JLabel txtEmployeeID;
    private javax.swing.JLabel txtFirstName;
    private javax.swing.JLabel txtLastName;
    private javax.swing.JLabel txtMiddleName;
    // End of variables declaration//GEN-END:variables
}
